"""Notebook-oriented visualization helpers (not used in graded batch output)."""

from pdiseg.debug.reload import assert_pipeline_schema, reload_pipeline_modules
from pdiseg.debug.sample import (
    DebugFrameResult,
    DebugFrameView,
    DebugSampleReport,
    build_sample_views,
    resolve_frame_snapshot,
    run_debug_sample,
    select_sample_images,
)
from pdiseg.debug.viz import (
    FrameDebugSnapshot,
    analyze_frame,
    debug_frame,
    draw_boxes,
    feature_summary,
    list_bundle_artifacts,
    plot_all_crops,
    plot_all_detection_stage,
    plot_all_frame_pipelines,
    plot_all_mask_layers,
    plot_all_masks,
    plot_all_overlays,
    plot_all_preprocess_stages,
    plot_all_preprocessed,
    plot_bundle_gallery,
    plot_frame_full_debug,
    plot_frame_masks,
    plot_frame_pipeline,
    save_debug_bundle,
    scored_table,
    to_rgb,
    visualize_masks,
    visualize_opened_background,
)

__all__ = [
    "DebugFrameResult",
    "DebugFrameView",
    "DebugSampleReport",
    "FrameDebugSnapshot",
    "analyze_frame",
    "assert_pipeline_schema",
    "build_sample_views",
    "debug_frame",
    "draw_boxes",
    "feature_summary",
    "list_bundle_artifacts",
    "plot_all_crops",
    "plot_all_detection_stage",
    "plot_all_frame_pipelines",
    "plot_all_mask_layers",
    "plot_all_masks",
    "plot_all_overlays",
    "plot_all_preprocess_stages",
    "plot_all_preprocessed",
    "plot_bundle_gallery",
    "plot_frame_full_debug",
    "plot_frame_masks",
    "plot_frame_pipeline",
    "reload_pipeline_modules",
    "resolve_frame_snapshot",
    "run_debug_sample",
    "save_debug_bundle",
    "scored_table",
    "select_sample_images",
    "to_rgb",
    "visualize_masks",
    "visualize_opened_background",
]
