"""Poultry packaging name-label segmentation (classical PDI, IFG).

Public API re-exports stable symbols for notebooks, tests, and scripts.
Internal layout is split under :mod:`pdiseg.core`, :mod:`pdiseg.detection`,
:mod:`pdiseg.runtime`, etc. See ``docs/src/ARCHITECTURE.md``.
"""

from pdiseg.calibration.service import ClassStats, calibrate
from pdiseg.core.imaging import BBox, FrameInspection, crop, render_overlay
from pdiseg.debug.reload import assert_pipeline_schema, reload_pipeline_modules
from pdiseg.debug.sample import (
    DebugFrameResult,
    DebugFrameView,
    DebugSampleReport,
    build_sample_views,
    resolve_frame_snapshot,
    run_debug_sample,
    select_sample_images,
)
from pdiseg.debug.viz import (
    FrameDebugSnapshot,
    analyze_frame,
    debug_frame,
    draw_boxes,
    feature_summary,
    list_bundle_artifacts,
    plot_all_crops,
    plot_all_detection_stage,
    plot_all_frame_pipelines,
    plot_all_mask_layers,
    plot_all_masks,
    plot_all_overlays,
    plot_all_preprocess_stages,
    plot_all_preprocessed,
    plot_bundle_gallery,
    plot_frame_full_debug,
    plot_frame_masks,
    plot_frame_pipeline,
    save_debug_bundle,
    scored_table,
    to_rgb,
    visualize_masks,
    visualize_opened_background,
)
from pdiseg.detection.candidates import detect_clusters, find_candidate_boxes
from pdiseg.detection.config import DetectionConfig
from pdiseg.detection.detector import (
    DetectionResult,
    detect,
    detect_name_labels,
    inspect_detection,
    inspect_frame,
)
from pdiseg.detection.masks import build_candidate_masks
from pdiseg.detection.postprocess import (
    expand_to_label_cluster,
    extract_product_anchor,
    group_label_fragments,
    keep_label_clusters,
    postprocess_boxes,
    refine_to_name_label,
)
from pdiseg.detection.preprocess import preprocess, preprocess_image
from pdiseg.detection.scoring import ScoredCandidate, score_candidate
from pdiseg.io.dataset import (
    FPS_OVERLAY_REGION,
    count_images_per_class,
    find_source_images,
    list_classes,
    load_image,
)
from pdiseg.recognition.classify import (
    UNKNOWN,
    Prediction,
    Template,
    classify_features,
    classify_segment,
    load_templates,
)
from pdiseg.recognition.config import RecognitionConfig
from pdiseg.recognition.features import Features, extract_descriptors, extract_features
from pdiseg.recognition.matching import match_fraction
from pdiseg.runtime.pipeline import (
    ClassReport,
    DatasetReport,
    RunSummary,
    crop_and_save,
    dump_preprocessed,
    output_path,
    process_dataset,
    run,
)

__all__ = [
    "FPS_OVERLAY_REGION",
    "UNKNOWN",
    "BBox",
    "ClassReport",
    "ClassStats",
    "DatasetReport",
    "DebugFrameResult",
    "DebugFrameView",
    "DebugSampleReport",
    "DetectionConfig",
    "DetectionResult",
    "Features",
    "FrameDebugSnapshot",
    "FrameInspection",
    "Prediction",
    "RecognitionConfig",
    "RunSummary",
    "ScoredCandidate",
    "Template",
    "analyze_frame",
    "assert_pipeline_schema",
    "build_candidate_masks",
    "build_sample_views",
    "calibrate",
    "classify_features",
    "classify_segment",
    "count_images_per_class",
    "crop",
    "crop_and_save",
    "debug_frame",
    "detect",
    "detect_clusters",
    "detect_name_labels",
    "draw_boxes",
    "dump_preprocessed",
    "expand_to_label_cluster",
    "extract_descriptors",
    "extract_features",
    "extract_product_anchor",
    "feature_summary",
    "find_candidate_boxes",
    "find_source_images",
    "group_label_fragments",
    "inspect_detection",
    "inspect_frame",
    "keep_label_clusters",
    "list_bundle_artifacts",
    "list_classes",
    "load_image",
    "load_templates",
    "match_fraction",
    "output_path",
    "plot_all_crops",
    "plot_all_detection_stage",
    "plot_all_frame_pipelines",
    "plot_all_mask_layers",
    "plot_all_masks",
    "plot_all_overlays",
    "plot_all_preprocess_stages",
    "plot_all_preprocessed",
    "plot_bundle_gallery",
    "plot_frame_full_debug",
    "plot_frame_masks",
    "plot_frame_pipeline",
    "postprocess_boxes",
    "preprocess",
    "preprocess_image",
    "process_dataset",
    "refine_to_name_label",
    "reload_pipeline_modules",
    "render_overlay",
    "resolve_frame_snapshot",
    "run",
    "run_debug_sample",
    "save_debug_bundle",
    "score_candidate",
    "scored_table",
    "select_sample_images",
    "to_rgb",
    "visualize_masks",
    "visualize_opened_background",
]
